sudo: required
dist: trusty
services:
  - docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
install:
  - yarn install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run uidev &
  - scripts/serverUpChecker.sh
script:
  - yarn test:e2e
  - sh build_docker.sh
