sudo: required
dist: trusty
services:
  - docker
language: node_js
node_js:
  - 10.16.3
cache: yarn
install:
  - yarn install --network-concurrency 1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn run uidev &
  - yarn test
  - yarn lint
  - scripts/serverUpChecker.sh
script:
  - ./bin/build.sh
