export const SET_EMAIL = "API_SET_EMAIL";
export const REQUEST_INIT_SESSION = "API_REQUEST_INIT_SESSION";
export const RECEIVE_INIT_SESSION = "API_RECEIVE_INIT_SESSION";
export const REQUEST_ME = "API_REQUEST_ME";
export const RECEIVE_ME = "API_RECEIVE_ME";
export const UPDATE_ME = "UPDATE_ME";
export const REQUEST_POLICY = "API_REQUEST_POLICY";
export const RECEIVE_POLICY = "API_RECEIVE_POLICY";
export const REQUEST_NEW_USER = "API_REQUEST_NEW_USER";
export const RECEIVE_NEW_USER = "API_RECEIVE_NEW_USER";
export const RECEIVE_PAYWALL_PAYMENT_WITH_FAUCET = "RECEIVE_PAYWALL_PAYMENT_WITH_FAUCET";
export const REQUEST_PAYWALL_PAYMENT_WITH_FAUCET = "REQUEST_PAYWALL_PAYMENT_WITH_FAUCET";
export const UPDATE_USER_PAYWALL_STATUS = "UPDATE_USER_PAYWALL_STATUS";
export const REQUEST_CHANGE_USERNAME = "API_REQUEST_CHANGE_USERNAME";
export const RECEIVE_CHANGE_USERNAME = "API_RECEIVE_CHANGE_USERNAME";
export const REQUEST_CHANGE_PASSWORD = "API_REQUEST_CHANGE_PASSWORD";
export const RECEIVE_CHANGE_PASSWORD = "API_RECEIVE_CHANGE_PASSWORD";
export const RESET_NEW_USER = "API_RESET_NEW_USER";
export const REQUEST_VERIFY_NEW_USER = "API_REQUEST_VERIFY_NEW_USER";
export const RECEIVE_VERIFY_NEW_USER = "API_RECEIVE_VERIFY_NEW_USER";
export const REQUEST_LOGIN = "API_REQUEST_LOGIN";
export const RECEIVE_LOGIN = "API_RECEIVE_LOGIN";
export const KEY_MISMATCH = "KEY_MISMATCH";
export const REQUEST_FORGOTTEN_PASSWORD_REQUEST = "API_REQUEST_FORGOTTEN_PASSWORD_REQUEST";
export const RECEIVE_FORGOTTEN_PASSWORD_REQUEST = "API_RECEIVE_FORGOTTEN_PASSWORD_REQUEST";
export const RESET_FORGOTTEN_PASSWORD_REQUEST = "API_RESET_FORGOTTEN_PASSWORD_REQUEST";
export const REQUEST_RESEND_VERIFICATION_EMAIL = "API_REQUEST_RESEND_VERIFICATION_EMAIL";
export const RECEIVE_RESEND_VERIFICATION_EMAIL = "API_RECEIVE_RESEND_VERIFICATION_EMAIL";
export const RESET_RESEND_VERIFICATION_EMAIL = "API_RESET_RESEND_VERIFICATION_EMAIL";
export const REQUEST_PASSWORD_RESET_REQUEST = "API_REQUEST_PASSWORD_RESET_REQUEST";
export const RECEIVE_PASSWORD_RESET_REQUEST = "API_RECEIVE_PASSWORD_RESET_REQUEST";
export const RESET_PASSWORD_RESET_REQUEST = "API_RESET_PASSWORD_RESET_REQUEST";
export const REQUEST_LOGOUT = "API_REQUEST_LOGOUT";
export const RECEIVE_LOGOUT = "API_RECEIVE_LOGOUT";
export const REQUEST_USER_PROPOSALS = "API_REQUEST_USER_PROPOSALS";
export const RECEIVE_USER_PROPOSALS = "API_RECEIVE_USER_PROPOSALS";
export const REQUEST_VETTED = "API_REQUEST_VETTED";
export const RECEIVE_VETTED = "API_RECEIVE_VETTED";
export const REQUEST_UNVETTED = "API_REQUEST_UNVETTED";
export const RECEIVE_UNVETTED = "API_RECEIVE_UNVETTED";
export const REQUEST_PROPOSAL = "API_REQUEST_PROPOSAL";
export const RECEIVE_PROPOSAL = "API_RECEIVE_PROPOSAL";
export const REQUEST_PROPOSAL_COMMENTS = "API_REQUEST_PROPOSAL_COMMENTS";
export const RECEIVE_PROPOSAL_COMMENTS = "API_RECEIVE_PROPOSAL_COMMENTS";
export const REQUEST_NEW_PROPOSAL = "API_REQUEST_NEW_PROPOSAL";
export const RECEIVE_NEW_PROPOSAL = "API_RECEIVE_NEW_PROPOSAL";
export const REQUEST_NEW_COMMENT = "API_REQUEST_NEW_COMMENT";
export const RECEIVE_NEW_COMMENT = "API_RECEIVE_NEW_COMMENT";
export const RESET_PROPOSAL = "API_RESET_PROPOSAL";
export const REQUEST_SETSTATUS_PROPOSAL = "API_REQUEST_SETSTATUS_PROPOSAL";
export const RECEIVE_SETSTATUS_PROPOSAL = "API_RECEIVE_SETSTATUS_PROPOSAL";
export const SET_PROPOSAL_APPROVED = "SET_PROPOSAL_APPROVED";
export const SET_VOTES_END_HEIGHT = "SET_VOTES_END_HEIGHT";
export const REQUEST_START_VOTE = "API_REQUEST_START_VOTE";
export const RECEIVE_START_VOTE = "API_RECEIVE_START_VOTE";
export const REQUEST_UPDATED_KEY = "API_REQUEST_UPDATED_KEY";
export const RECEIVE_UPDATED_KEY = "API_RECEIVE_UPDATED_KEY";
export const REQUEST_VERIFIED_KEY = "API_REQUEST_VERIFIED_KEY";
export const RECEIVE_VERIFIED_KEY = "API_RECEIVE_VERIFIED_KEY";
export const REQUEST_USERNAMES_BY_ID = "API_REQUEST_USERNAMES_BY_ID";
export const RECEIVE_USERNAMES_BY_ID = "API_RECEIVE_USERNAMES_BY_ID";
export const REDIRECTED_FROM = "REDIRECTED_FROM";
export const RESET_REDIRECTED_FROM = "RESET_REDIRECTED_FROM";
export const CHANGE_ADMIN_FILTER_VALUE = "CHANGE_ADMIN_FILTER_VALUE";
export const CHANGE_PUBLIC_FILTER_VALUE = "CHANGE_PUBLIC_FILTER_VALUE";

export const REQUEST_LIKE_COMMENT = "API_REQUEST_LIKE_COMMENT";
export const RECEIVE_LIKE_COMMENT = "API_RECEIVE_LIKE_COMMENT";

export const REQUEST_LIKED_COMMENTS = "API_REQUEST_LIKED_COMMENTS";
export const RECEIVE_LIKED_COMMENTS = "API_RECEIVE_LIKED_COMMENTS";

export const REQUEST_PROPOSAL_VOTE_STATUS = "API_REQUEST_PROPOSAL_VOTE_STATUS";
export const RECEIVE_PROPOSAL_VOTE_STATUS = "API_RECEIVE_PROPOSAL_VOTE_STATUS";

export const REQUEST_PROPOSALS_VOTE_STATUS = "API_REQUEST_PROPOSALS_VOTE_STATUS";
export const RECEIVE_PROPOSALS_VOTE_STATUS = "API_RECEIVE_PROPOSALS_VOTE_STATUS";

export const LOAD_ME = "LOAD_ME";

export const CLEAN_ERRORS = "CLEAN_ERRORS";
export const CLEAN_SLATE = "CLEAN_SLATE";

export const REQUEST_SIGNUP_CONFIRMATION = "REQUEST_SIGNUP_CONFIRMATION";
export const RESET_SIGNUP_CONFIRMATION = "RESET_SIGNUP_CONFIRMATION";
export const SET_REPLY_PARENT = "SET_REPLY_PARENT";
export const RECEIVE_USERNAMES = "SET_USERNAMES";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const REQUEST_GET_LAST_BLOCK_HEIGHT = "EXTERNAL_API_REQUEST_GET_LAST_BLOCK_HEIGHT";
export const RECEIVE_GET_LAST_BLOCK_HEIGHT = "EXTERNAL_API_RECEIVE_GET_LAST_BLOCK_HEIGHT";

export const CSRF_NEEDED = "API_CSRF_NEEDED";
export const SHOULD_AUTO_VERIFY_KEY= "API_SHOULD_AUTO_VERIFY_KEY";

export const IDENTITY_IMPORTED = "IDENTITY_IMPORTED";
