export const SET_EMAIL = "API_SET_EMAIL";
export const REQUEST_INIT_SESSION = "API_REQUEST_INIT_SESSION";
export const RECEIVE_INIT_SESSION = "API_RECEIVE_INIT_SESSION";
export const REQUEST_ME = "API_REQUEST_ME";
export const RECEIVE_ME = "API_RECEIVE_ME";
export const UPDATE_ME = "UPDATE_ME";
export const REQUEST_POLICY = "API_REQUEST_POLICY";
export const RECEIVE_POLICY = "API_RECEIVE_POLICY";
export const REQUEST_NEW_USER = "API_REQUEST_NEW_USER";
export const RECEIVE_NEW_USER = "API_RECEIVE_NEW_USER";
export const RECEIVE_PAYWALL_PAYMENT_WITH_FAUCET =
  "RECEIVE_PAYWALL_PAYMENT_WITH_FAUCET";
export const REQUEST_PAYWALL_PAYMENT_WITH_FAUCET =
  "REQUEST_PAYWALL_PAYMENT_WITH_FAUCET";
export const RESET_PAYWALL_PAYMENT_WITH_FAUCET =
  "RESET_PAYWALL_PAYMENT_WITH_FAUCET";
export const UPDATE_USER_PAYWALL_STATUS = "UPDATE_USER_PAYWALL_STATUS";
export const SET_PROPOSAL_CREDITS = "SET_PROPOSAL_CREDITS";
export const ADD_PROPOSAL_CREDITS = "ADD_PROPOSAL_CREDITS";
export const SUBTRACT_PROPOSAL_CREDITS = "SUBTRACT_PROPOSAL_CREDITS";
export const REQUEST_CHANGE_USERNAME = "API_REQUEST_CHANGE_USERNAME";
export const RECEIVE_CHANGE_USERNAME = "API_RECEIVE_CHANGE_USERNAME";
export const REQUEST_CHANGE_PASSWORD = "API_REQUEST_CHANGE_PASSWORD";
export const RECEIVE_CHANGE_PASSWORD = "API_RECEIVE_CHANGE_PASSWORD";
export const RESET_NEW_USER = "API_RESET_NEW_USER";
export const REQUEST_VERIFY_NEW_USER = "API_REQUEST_VERIFY_NEW_USER";
export const RECEIVE_VERIFY_NEW_USER = "API_RECEIVE_VERIFY_NEW_USER";
export const REQUEST_USER = "API_REQUEST_USER";
export const RECEIVE_USER = "API_RECEIVE_USER";
export const REQUEST_LOGIN = "API_REQUEST_LOGIN";
export const RECEIVE_LOGIN = "API_RECEIVE_LOGIN";
export const KEY_MISMATCH = "KEY_MISMATCH";
export const REQUEST_FORGOTTEN_PASSWORD_REQUEST =
  "API_REQUEST_FORGOTTEN_PASSWORD_REQUEST";
export const RECEIVE_FORGOTTEN_PASSWORD_REQUEST =
  "API_RECEIVE_FORGOTTEN_PASSWORD_REQUEST";
export const RESET_FORGOTTEN_PASSWORD_REQUEST =
  "API_RESET_FORGOTTEN_PASSWORD_REQUEST";
export const REQUEST_RESEND_VERIFICATION_EMAIL =
  "API_REQUEST_RESEND_VERIFICATION_EMAIL";
export const RECEIVE_RESEND_VERIFICATION_EMAIL =
  "API_RECEIVE_RESEND_VERIFICATION_EMAIL";
export const RESET_RESEND_VERIFICATION_EMAIL =
  "API_RESET_RESEND_VERIFICATION_EMAIL";
export const REQUEST_PASSWORD_RESET_REQUEST =
  "API_REQUEST_PASSWORD_RESET_REQUEST";
export const RECEIVE_PASSWORD_RESET_REQUEST =
  "API_RECEIVE_PASSWORD_RESET_REQUEST";
export const RESET_PASSWORD_RESET_REQUEST = "API_RESET_PASSWORD_RESET_REQUEST";
export const REQUEST_LOGOUT = "API_REQUEST_LOGOUT";
export const RECEIVE_LOGOUT = "API_RECEIVE_LOGOUT";
export const REQUEST_USER_PROPOSALS = "API_REQUEST_USER_PROPOSALS";
export const RECEIVE_USER_PROPOSALS = "API_RECEIVE_USER_PROPOSALS";
export const REQUEST_VETTED = "API_REQUEST_VETTED";
export const RECEIVE_VETTED = "API_RECEIVE_VETTED";
export const REQUEST_UNVETTED = "API_REQUEST_UNVETTED";
export const RECEIVE_UNVETTED = "API_RECEIVE_UNVETTED";
export const REQUEST_PROPOSAL = "API_REQUEST_PROPOSAL";
export const RECEIVE_PROPOSAL = "API_RECEIVE_PROPOSAL";
export const REQUEST_PROPOSAL_COMMENTS = "API_REQUEST_PROPOSAL_COMMENTS";
export const RECEIVE_PROPOSAL_COMMENTS = "API_RECEIVE_PROPOSAL_COMMENTS";
export const REQUEST_NEW_PROPOSAL = "API_REQUEST_NEW_PROPOSAL";
export const RECEIVE_NEW_PROPOSAL = "API_RECEIVE_NEW_PROPOSAL";

export const REQUEST_EDIT_PROPOSAL = "API_REQUEST_EDIT_PROPOSAL";
export const RECEIVE_EDIT_PROPOSAL = "API_RECEIVE_EDIT_PROPOSAL";
export const REQUEST_NEW_COMMENT = "API_REQUEST_NEW_COMMENT";
export const RECEIVE_NEW_COMMENT = "API_RECEIVE_NEW_COMMENT";
export const RESET_PROPOSAL = "API_RESET_PROPOSAL";
export const RESET_INVOICE = "API_RESET_INVOICE";
export const REQUEST_SETSTATUS_PROPOSAL = "API_REQUEST_SETSTATUS_PROPOSAL";
export const RECEIVE_SETSTATUS_PROPOSAL = "API_RECEIVE_SETSTATUS_PROPOSAL";
export const SET_PROPOSAL_APPROVED = "SET_PROPOSAL_APPROVED";
export const SET_VOTES_END_HEIGHT = "SET_VOTES_END_HEIGHT";
export const REQUEST_START_VOTE = "API_REQUEST_START_VOTE";
export const RECEIVE_START_VOTE = "API_RECEIVE_START_VOTE";
export const REQUEST_UPDATED_KEY = "API_REQUEST_UPDATED_KEY";
export const RECEIVE_UPDATED_KEY = "API_RECEIVE_UPDATED_KEY";
export const REQUEST_VERIFIED_KEY = "API_REQUEST_VERIFIED_KEY";
export const RECEIVE_VERIFIED_KEY = "API_RECEIVE_VERIFIED_KEY";
export const REQUEST_USERNAMES_BY_ID = "API_REQUEST_USERNAMES_BY_ID";
export const RECEIVE_USERNAMES_BY_ID = "API_RECEIVE_USERNAMES_BY_ID";
export const REDIRECTED_FROM = "REDIRECTED_FROM";
export const RESET_REDIRECTED_FROM = "RESET_REDIRECTED_FROM";
export const CHANGE_ADMIN_FILTER_VALUE = "CHANGE_ADMIN_FILTER_VALUE";
export const CHANGE_PUBLIC_FILTER_VALUE = "CHANGE_PUBLIC_FILTER_VALUE";
export const CHANGE_USER_FILTER_VALUE = "CHANGE_USER_FILTER_VALUE";
export const CHANGE_DATE_FILTER = "CHANGE_DATE_FILTER";
export const RESET_DATE_FILTER = "RESET_DATE_FILTER";

export const REQUEST_LIKE_COMMENT = "API_REQUEST_LIKE_COMMENT";
export const RECEIVE_LIKE_COMMENT = "API_RECEIVE_LIKE_COMMENT";
export const RECEIVE_SYNC_LIKE_COMMENT = "RECEIVE_SYNC_LIKE_COMMENT";
export const RESET_SYNC_LIKE_COMMENT = "RESET_SYNC_LIKE_COMMENT";

export const REQUEST_CENSOR_COMMENT = "API_REQUEST_CENSOR_COMMENT";
export const RECEIVE_CENSOR_COMMENT = "API_RECEIVE_CENSOR_COMMENT";

export const REQUEST_LIKED_COMMENTS = "API_REQUEST_LIKED_COMMENTS";
export const RECEIVE_LIKED_COMMENTS = "API_RECEIVE_LIKED_COMMENTS";

export const REQUEST_UNVETTED_STATUS = "API_REQUEST_UNVETTED_STATUS";
export const RECEIVE_UNVETTED_STATUS = "API_RECEIVE_UNVETTED_STATUS";

export const REQUEST_EDIT_USER = "API_REQUEST_EDIT_USER";
export const RECEIVE_EDIT_USER = "API_RECEIVE_EDIT_USER";
export const RESET_EDIT_USER = "API_RESET_EDIT_USER";

export const REQUEST_MANAGE_USER = "API_REQUEST_MANAGE_USER";
export const RECEIVE_MANAGE_USER = "API_RECEIVE_MANAGE_USER";

export const REQUEST_PROPOSAL_VOTE_STATUS = "API_REQUEST_PROPOSAL_VOTE_STATUS";
export const RECEIVE_PROPOSAL_VOTE_STATUS = "API_RECEIVE_PROPOSAL_VOTE_STATUS";

export const REQUEST_PROPOSAL_VOTE_RESULTS =
  "API_REQUEST_PROPOSAL_VOTE_RESULTS";
export const RECEIVE_PROPOSAL_VOTE_RESULTS =
  "API_RECEIVE_PROPOSAL_VOTE_RESULTS";

export const REQUEST_PROPOSALS_VOTE_STATUS =
  "API_REQUEST_PROPOSALS_VOTE_STATUS";
export const RECEIVE_PROPOSALS_VOTE_STATUS =
  "API_RECEIVE_PROPOSALS_VOTE_STATUS";

export const REQUEST_USER_SEARCH = "API_REQUEST_USER_SEARCH";
export const RECEIVE_USER_SEARCH = "API_RECEIVE_USER_SEARCH";

export const SAVE_DRAFT_PROPOSAL = "SAVE_DRAFT_PROPOSAL";
export const DELETE_DRAFT_PROPOSAL = "DELETE_DRAFT_PROPOSAL";
export const LOAD_DRAFT_PROPOSALS = "LOAD_DRAFT_PROPOSALS";

export const REQUEST_SET_VISITED_PROPOSAL = "REQUEST_SET_VISITED_PROPOSAL";
export const RECEIVE_SET_VISITED_PROPOSAL = "RECEIVE_SET_VISITED_PROPOSAL";
export const REQUEST_GET_VISITED_PROPOSAL = "REQUEST_GET_VISITED_PROPOSAL";
export const RECEIVE_GET_VISITED_PROPOSAL = "RECEIVE_GET_VISITED_PROPOSAL";

export const SAVE_PAYMENT_POLLING_QUEUE = "SAVE_PAYMENT_POLLING_QUEUE";
export const UPDATE_PAYMENT_POLLING_QUEUE = "UPDATE_PAYMENT_POLLING_QUEUE";
export const SET_PAYMENT_POLLING_QUEUE = "SET_PAYMENT_POLLING_QUEUE";

export const REQUEST_PROPOSAL_PAYWALL_DETAILS =
  "API_REQUEST_PROPOSAL_PAYWALL_DETAILS";
export const RECEIVE_PROPOSAL_PAYWALL_DETAILS =
  "API_RECEIVE_PROPOSAL_PAYWALL_DETAILS";
export const REQUEST_UPDATE_PROPOSAL_CREDITS =
  "API_REQUEST_UPDATE_PROPOSAL_CREDITS";
export const RECEIVE_UPDATE_PROPOSAL_CREDITS =
  "API_RECEIVE_UPDATE_PROPOSAL_CREDITS";
export const REQUEST_USER_PROPOSAL_CREDITS =
  "API_REQUEST_USER_PROPOSAL_CREDITS";
export const RECEIVE_USER_PROPOSAL_CREDITS =
  "API_RECEIVE_USER_PROPOSAL_CREDITS";

export const LOAD_ME = "LOAD_ME";

export const CLEAN_ERRORS = "CLEAN_ERRORS";

export const REQUEST_SIGNUP_CONFIRMATION = "REQUEST_SIGNUP_CONFIRMATION";
export const RESET_SIGNUP_CONFIRMATION = "RESET_SIGNUP_CONFIRMATION";
export const SET_REPLY_PARENT = "SET_REPLY_PARENT";
export const RECEIVE_USERNAMES = "SET_USERNAMES";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const CLOSE_ALL_MODALS = "CLOSE_ALL_MODALS";
export const CONFIRM_MODAL = "CONFIRM_WITH_MODAL";

export const RECEIVE_NEW_THREAD_COMMENT = "RECEIVE_NEW_THREAD_COMMENT";

export const REQUEST_GET_LAST_BLOCK_HEIGHT =
  "EXTERNAL_API_REQUEST_GET_LAST_BLOCK_HEIGHT";
export const RECEIVE_GET_LAST_BLOCK_HEIGHT =
  "EXTERNAL_API_RECEIVE_GET_LAST_BLOCK_HEIGHT";

export const CSRF_NEEDED = "API_CSRF_NEEDED";
export const SHOULD_AUTO_VERIFY_KEY = "API_SHOULD_AUTO_VERIFY_KEY";

export const IDENTITY_IMPORTED = "IDENTITY_IMPORTED";

export const RESET_LAST_SUBMITTED = "RESET_LAST_SUBMITTED";

export const SET_ONBOARD_AS_VIEWED = "SET_ONBOARD_AS_VIEWED";

export const SET_COMMENTS_SORT_OPTION = "SET_COMMENTS_SORT_OPTION";

export const REQUEST_AUTHORIZE_VOTE = "REQUEST_AUTHORIZE_VOTE";
export const RECEIVE_AUTHORIZE_VOTE = "RECEIVE_AUTHORIZE_VOTE";

export const RECEIVE_REVOKE_AUTH_VOTE = "RECEIVE_REVOKE_AUTH_VOTE";

export const REQUEST_PROPOSAL_PAYWALL_PAYMENT =
  "REQUEST_PROPOSAL_PAYWALL_PAYMENT";
export const RECEIVE_PROPOSAL_PAYWALL_PAYMENT =
  "RECEIVE_PROPOSAL_PAYWALL_PAYMENT";

export const TOGGLE_CREDITS_PAYMENT_POLLING = "TOGGLE_CREDITS_PAYMENT_POLLING";
export const TOGGLE_PROPOSAL_PAYMENT_RECEIVED =
  "TOGGLE_PROPOSAL_PAYMENT_RECEIVED";

export const RESET_PAYWALL_INFO = "RESET_PAYWALL_INFO";

export const REQUEST_RESCAN_USER_PAYMENTS = "REQUEST_RESCAN_USER_PAYMENTS";
export const RECEIVE_RESCAN_USER_PAYMENTS = "RECEIVE_RESCAN_USER_PAYMENTS";
export const RESET_RESCAN_USER_PAYMENTS = "RESET_RESCAN_USER_PAYMENTS";

export const REQUEST_TOKEN_INVENTORY = "REQUEST_TOKEN_INVENTORY";
export const RECEIVE_TOKEN_INVENTORY = "RECEIVE_TOKEN_INVENTORY";

// CMS
export const REQUEST_INVITE_USER = "REQUEST_INVITE_USER";
export const RECEIVE_INVITE_USER = "RECEIVE_INVITE_USER";
export const RESET_INVITE_USER = "RESET_INVITE_USER";
export const REQUEST_NEW_INVOICE = "API_REQUEST_NEW_INVOICE";
export const RECEIVE_NEW_INVOICE = "API_RECEIVE_NEW_INVOICE";

export const REQUEST_EDIT_INVOICE = "API_REQUEST_EDIT_INVOICE";
export const RECEIVE_EDIT_INVOICE = "API_RECEIVE_EDIT_INVOICE";

export const REQUEST_USER_INVOICES = "API_REQUEST_USER_INVOICES";
export const RECEIVE_USER_INVOICES = "API_RECEIVE_USER_INVOICES";

export const REQUEST_ADMIN_INVOICES = "API_REQUEST_ADMIN_INVOICES";
export const RECEIVE_ADMIN_INVOICES = "API_RECEIVE_ADMIN_INVOICES";

export const REQUEST_INVOICE = "API_REQUEST_INVOICE";
export const RECEIVE_INVOICE = "API_RECEIVE_INVOICE";

export const REQUEST_INVOICE_COMMENTS = "API_REQUEST_INVOICE_COMMENTS";
export const RECEIVE_INVOICE_COMMENTS = "API_RECEIVE_INVOICE_COMMENTS";
export const RECEIVE_NEW_INVOICE_COMMENT = "API_RECEIVE_NEW_INVOICE_COMMENT";
export const RECEIVE_CENSOR_INVOICE_COMMENT =
  "API_RECEIVE_CENSOR_INVOICE_COMMENT";

export const REQUEST_SETSTATUS_INVOICE = "API_REQUEST_SETSTATUS_INVOICE";
export const RECEIVE_SETSTATUS_INVOICE = "API_RECEIVE_SETSTATUS_INVOICE";

export const REQUEST_GENERATE_PAYOUTS = "API_REQUEST_GENERATE_PAYOUTS";
export const RECEIVE_GENERATE_PAYOUTS = "API_RECEIVE_GENERATE_PAYOUTS";

export const REQUEST_EXCHANGE_RATE = "API_REQUEST_EXCHANGE_RATE";
export const RECEIVE_EXCHANGE_RATE = "API_RECEIVE_EXCHANGE_RATE";
