import React, { useState } from "react";
import { Card, Spinner, H2, P, CopyableText, Button } from "pi-ui";
import useTotp from "../hooks/useTotp";
import styles from "./Totp.module.css";
import DigitsInput from "src/components/DigitsInput";

const VerifyTotp = ({ onVerify }) => {
  const [enableVerify, setEnableVerify] = useState(false);
  const [code, setCode] = useState("");
  const onFillCode = (newCode) => {
    setEnableVerify(newCode.length === 6);
    setCode(newCode);
  };
  return (
    <div>
      <H2>Verify TOTP</H2>
      <P>
        TOTP Token already set. You can verify it by using the key generated by
        your TOTP authenticator.
      </P>
      <DigitsInput onChange={onFillCode} />
      <Button
        kind={enableVerify ? "primary" : "disabled"}
        onClick={onVerify(code)}>
        Verify
      </Button>
    </div>
  );
};

const SetTotp = ({ totp }) => {
  return (
    <div className="margin-bottom-m">
      <H2>Set TOTP Authentication</H2>
      <div className={styles.setContainer}>
        <div className={styles.qrcode}>
          {totp.image && (
            <img src={`data:image/png;base64, ${totp.image}`} alt={totp.key} />
          )}
        </div>
        <div className={styles.instructions}>
          <P>Step 1 - scan the QR Code with a TOTP Authenticator</P>
          <P>
            Step 2 - verify the 6-numbers code to activate the authentication
          </P>
          <div className={styles.copyableKey}>
            {totp.key && <CopyableText id="totp-key">{totp.key}</CopyableText>}
          </div>
        </div>
      </div>
    </div>
  );
};

const Totp = () => {
  const { loading, alreadySet, totp, onVerifyTotp } = useTotp();
  const handleVerify = (code) => (e) => {
    e && e.preventDefault();
    onVerifyTotp(code).catch((e) => {
      console.log(e);
      throw e;
    });
  };
  return loading ? (
    <Spinner invert />
  ) : (
    <Card paddingSize="small">
      {!alreadySet && <SetTotp totp={totp} />}
      <VerifyTotp onVerify={handleVerify} />
    </Card>
  );
};

export default Totp;
