import React from "react";
import { Card, Spinner, H2, P, NumberInput, CopyableText } from "pi-ui";
import useTotp from "../hooks/useTotp";
import FormWrapper from "src/components/FormWrapper";

const VerifyTotp = ({ onVerify }) => (
  <div>
    <H2>Verify TOTP</H2>
    <P>
      TOTP Token already set. You can verify it by using the key generated by
      your TOTP authenticator.
    </P>
    <FormWrapper initialValues={{ code: "" }} onSubmit={onVerify}>
      {({ values }) => (
        <NumberInput name="code" id="totp-code" value={values.code} />
      )}
    </FormWrapper>
  </div>
);
const SetTotp = ({ totp }) => {
  return (
    <div>
      <H2>SET TOTP</H2>
      <P>
        You can set your TOTP Authenticator by scanning the QR Code below, or
        using the following Key:
      </P>
      {totp.image && (
        <div className="margin-top-m margin-bottom-m justify-center">
          <img src={`data:image/png;base64, ${totp.image}`} alt={totp.key} />
        </div>
      )}
      {totp.key && (
        <div className="justify-center">
          <CopyableText id="totp-key">{totp.key}</CopyableText>
        </div>
      )}
    </div>
  );
};

const Totp = () => {
  const { loading, alreadySet, totp } = useTotp();
  console.log("state", totp);
  return loading ? (
    <Spinner invert />
  ) : (
    <Card paddingSize="small">
      {alreadySet ? <VerifyTotp /> : <SetTotp totp={totp} />}
    </Card>
  );
};

export default Totp;
