export const CONFIRM_ACTION = "CONFIRM_ACTION";
export const CONFIRM_ACTION_WITH_REASON = "CONFIRM_ACTION_WITH_REASON";
export const LOGIN = "LOGIN";
export const ONBOARD = "ONBOARD";
export const PAYWALL_MODAL = "PAYWALL_MODAL";
export const PURCHASE_CREDITS_MODAL = "PURCHASE_CREDITS_MODAL";
export const CREDITS_HISTORY_MODAL = "CREDITS_HISTORY_MODAL";
export const MANAGE_CREDITS_MODAL = "MANAGE_CREDITS_MODAL";
