export const CONFIRM_ACTION = "CONFIRM_ACTION";
export const CONFIRM_ACTION_WITH_REASON = "CONFIRM_ACTION_WITH_REASON";
export const LOGIN = "LOGIN";
export const ONBOARD = "ONBOARD";
export const PAYWALL_MODAL = "PAYWALL_MODAL";
