import {
  fetchRecordDetails,
  fetchRecordVersionDetails,
  fetchRecords,
  selectFullToken,
  selectRecordByShortToken,
  selectRecordByToken,
  selectRecordVersionByToken,
  selectRecordVersionStatusByToken,
  selectRecords,
  selectRecordsByStateAndStatus,
  selectRecordsByTokensBatch,
  selectRecordsError,
  selectRecordsStatus,
} from "./recordsSlice";

export const records = {
  fetch: fetchRecords,
  fetchDetails: fetchRecordDetails,
  selectFullToken: selectFullToken,
  fetchVersionDetails: fetchRecordVersionDetails,
  selectStatus: selectRecordsStatus,
  selectError: selectRecordsError,
  selectByToken: selectRecordByToken,
  selectByShortToken: selectRecordByShortToken,
  selectVersionByToken: selectRecordVersionByToken,
  selectVersionStatusByToken: selectRecordVersionStatusByToken,
  selectByTokensBatch: selectRecordsByTokensBatch,
  selectAll: selectRecords,
  selectByStateAndStatus: selectRecordsByStateAndStatus,
};
