name: Build and Test Plugins-structure App
on:
  push:
    paths:
      - plugins-structure/**
  pull_request:
    paths:
      - plugins-structure/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins-structure
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: xvfb run
        run: |
          export DISPLAY=:99.0
          Xvfb :99.0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
        working-directory: ./plugins-structure
      - name: yarn install
        run: yarn install --network-concurrency 1
        working-directory: ./plugins-structure
      - name: linter checks
        run: yarn lint:test
        working-directory: ./plugins-structure
      - name: pretty check
        run: yarn prettify:check
        working-directory: ./plugins-structure
      - name: tests
        run: yarn test
        working-directory: ./plugins-structure
        env:
          CI: true
